allowBuilds:
  esbuild: true
  unrs-resolver: true
  '@scarf/scarf@1.4.0': false
  'core-js-pure@3.50.0': false
  '@tree-sitter-grammars/tree-sitter-yaml@0.7.1': true
  'tree-sitter-json@0.24.8': true
  'tree-sitter@0.21.1 || 0.22.4': true
